apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tea-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '5'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: IMAGE_URI
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: EGG_SERVER_ENV
              value: prod
            - name: TZ
              value: Asia/Taipei
            - name: DISABLE_DB
              value: 'true'
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
